Repository uclapi/uclapi, pull requests merged in 2019-01, with the labels that each got.

#876 Updates requirements and migrates to redis-py 3.0 syntax
  backend/uclapi/common/decorators.py
  backend/uclapi/oauth/views.py
  backend/uclapi/requirements.txt
  backend/uclapi/roombookings/helpers.py
  backend/uclapi/roombookings/tests.py
  backend/uclapi/timetable/app_helpers.py
  backend/uclapi/timetable/tasks.py
  backend/uclapi/workspaces/image_builder.py
  backend/uclapi/workspaces/management/commands/get_occupeye_token.py
  backend/uclapi/workspaces/occupeye/api.py
  backend/uclapi/workspaces/occupeye/cache.py
  backend/uclapi/workspaces/tests.py
Labels: dependencies, enhancement

#932 Sets default AWS bucket access policy to public-read for statics
  backend/uclapi/uclapi/settings.py
Labels: ready to merge and deploy

#942 Remove link to now archived github repo
  frontend/src/components/documentation/GetInvolved/GetInvolved.jsx
  frontend/src/components/documentation/Routes/OAuth/Authorise.jsx
  frontend/src/components/documentation/Routes/OAuth/StudentNumber.jsx
  frontend/src/components/documentation/Routes/OAuth/Token.jsx
  frontend/src/components/documentation/Routes/OAuth/UserData.jsx
  frontend/src/components/documentation/Routes/Resources/DesktopAvailability.jsx
  frontend/src/components/documentation/Routes/RoomBookings/GetBookings.jsx
  frontend/src/components/documentation/Routes/RoomBookings/GetEquipment.jsx
  frontend/src/components/documentation/Routes/RoomBookings/GetFreeRooms.jsx
  frontend/src/components/documentation/Routes/RoomBookings/GetRooms.jsx
  frontend/src/components/documentation/Routes/Search/GetPeople.jsx
  frontend/src/components/documentation/Routes/Timetable/GetDataDepartments.jsx
  frontend/src/components/documentation/Routes/Timetable/GetDataModules.jsx
  frontend/src/components/documentation/Routes/Timetable/GetPersonalTimetable.jsx
  frontend/src/components/documentation/Routes/Timetable/GetTimetableByModules.jsx
  frontend/src/components/documentation/Routes/Workspaces/GetImage.jsx
  frontend/src/components/documentation/Routes/Workspaces/GetLastSensorUpdate.jsx
  frontend/src/components/documentation/Routes/Workspaces/GetLiveImage.jsx
  frontend/src/components/documentation/Routes/Workspaces/GetSensorHistoricalTimeData.jsx
  frontend/src/components/documentation/Routes/Workspaces/GetSensorSummary.jsx
  frontend/src/components/documentation/Routes/Workspaces/GetSensors.jsx
  frontend/src/components/documentation/Routes/Workspaces/GetSurveys.jsx
Labels: docs, ready to merge and deploy

#952 Removes seemingly unnecessary dotenv import in common.helpers
  backend/uclapi/common/helpers.py
  backend/uclapi/manage.py
Labels: enhancement

#953 Return correct message for no callback url
  backend/uclapi/oauth/tests.py
  backend/uclapi/oauth/views.py
Labels: bug

#940 Redis-based Last-Modified Header
  .gitignore
  backend/uclapi/common/decorators.py
  backend/uclapi/common/helpers.py
  backend/uclapi/common/tests.py
  backend/uclapi/oauth/tests.py
  backend/uclapi/oauth/views.py
  backend/uclapi/resources/views.py
  backend/uclapi/roombookings/helpers.py
  backend/uclapi/roombookings/management/commands/update_gencache.py
  backend/uclapi/roombookings/views.py
  backend/uclapi/search/views.py
  backend/uclapi/timetable/management/commands/update_timetable_gencache.py
  backend/uclapi/timetable/views.py
  backend/uclapi/workspaces/occupeye/cache.py
  backend/uclapi/workspaces/views.py
  frontend/src/components/documentation/Meta/Welcome.jsx
  frontend/src/components/documentation/Sidebar.jsx
Labels: enhancement

#959 Re-adds read_dotenv, but with super powers
  backend/uclapi/manage.py
Labels: bug

#951 Slimming treatment for dashboard static assets
  .gitignore
  .travis.yml
  backend/uclapi/dashboard/templates/dashboard.html
  backend/uclapi/dashboard/templates/documentation.html
  backend/uclapi/dashboard/templates/getStarted.html
  backend/uclapi/marketplace/templates/marketplace.html
  backend/uclapi/oauth/templates/permissions.html
  backend/uclapi/requirements.txt
  backend/uclapi/uclapi/settings.py
  backend/uclapi/webpack-stats.sample.json
  frontend/.babelrc
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: javascript

#979 Fix travis
  .travis.yml
Labels: high priority
