Repository uclapi/uclapi, pull requests merged in 2019-11, with the labels that each got.

#1349 Increase test coverage
  backend/uclapi/timetable/tests.py
  backend/uclapi/timetable/views.py
Labels: WIP

#1840 Fix date on dashboard
  frontend/src/components/dashboard/relativeDate.jsx
Labels: bug

#1892 Update locations of workspaces
  backend/uclapi/workspaces/occupeye/constants.py
Labels: ready to merge and deploy, workspaces

#1802 Django2 migration
  .travis.yml
  backend/uclapi/dashboard/models.py
  backend/uclapi/requirements.txt
  backend/uclapi/timetable/models.py
  backend/uclapi/uclapi/urls.py
Labels: WIP

#1894 Remove oracle connection in test
  backend/uclapi/roombookings/tests.py
Labels: python, ready to merge and deploy
