Repository uclapi/uclapi, pull requests merged in 2019-10, with the labels that each got.

#1703 Fix Duplicate Lab Timetable Bug
  backend/uclapi/timetable/management/commands/test_personal_timetable.py
  backend/uclapi/timetable/sql/generate_student_timetable_template.sql
Labels: timetable

#1611 Add Dependabot Config
  .dependabot/config.yml
Labels: dependencies, enhancement

#1347 Compress frontend assets
  frontend/.babelrc
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/dashboard/app.jsx
  frontend/src/components/dashboard/app/OAuthScopesForm.jsx
  frontend/src/components/dashboard/appList.jsx
  frontend/src/components/dashboard/relativeDate.jsx
  frontend/src/components/documentation/LanguageTabs.jsx
  frontend/src/components/documentation/Routes/OAuth/Token.jsx
  frontend/src/components/documentation/Topic.jsx
  frontend/src/components/getStarted/API.jsx
  frontend/src/components/getStarted/Demo.jsx
  frontend/src/components/getStarted/FAQ.jsx
  frontend/src/components/getStarted/QandA.jsx
  frontend/src/pages/appsettings.jsx
  frontend/src/pages/dashboard.jsx
  frontend/webpack.prod.js
Labels: javascript, ready to merge and deploy
