Repository uclapi/uclapi, pull requests merged in 2019-02, with the labels that each got.

#981 [WIP] Migrates us to a custom build of django-webpack-loader
  .travis.yml
  backend/uclapi/requirements.txt
  backend/uclapi/uclapi/settings.py
  backend/uclapi/uclapi/wsgi.py
  frontend/webpack.dev.js
Labels: enhancement

#989 Timetable speed-up
  backend/uclapi/timetable/app_helpers.py
  backend/uclapi/timetable/management/commands/test_personal_timetable.py
  frontend/src/components/documentation/Routes/OAuth/OAuthIntro.jsx
Labels: ready to merge and deploy

#1001 Adds access_token in response
  backend/uclapi/oauth/views.py
Labels: bug, enhancement, high priority

#1014 Ensures that even bad trigger types are stringified to avoid Redis errors
  backend/uclapi/workspaces/occupeye/cache.py
Labels: bug, high priority

#1028 Medium fix
  backend/uclapi/dashboard/app_helpers.py
Labels: bug, ready to merge and deploy

#1018 New Dev Docker Environment
  .dockerignore
  backend/uclapi/common/management/commands/dev_environment_setup.py
  dev.Dockerfile
  docker-compose-prod.yml
  docker-compose.yml
  docker/.env.example
  docker/fakeshibboleth.Dockerfile
  docker/oauth-test.Dockerfile
  docker/uclapi-dev.Dockerfile
  frontend/package-lock.json
  prod.Dockerfile
  scripts/dev.Dockerfile
  scripts/devrun.sh
  scripts/nginx/fastcgi.conf
  scripts/nginx/fastcgi_params
  scripts/nginx/nginx.conf
  scripts/nginx/shib_clear_headers
  scripts/nginx/shib_fastcgi_params
  scripts/prod.sh
  scripts/prodrun.sh
  scripts/setup.sh
  scripts/shibboleth/README.md
  scripts/shibboleth/accessError.html
  scripts/shibboleth/attrChecker.html
  scripts/shibboleth/bindingTemplate.html
  scripts/shibboleth/console.logger
  scripts/shibboleth/discoveryTemplate.html
  scripts/shibboleth/globalLogout.html
  scripts/shibboleth/localLogout.html
  scripts/shibboleth/metadataError.html
  scripts/shibboleth/native.logger
  scripts/shibboleth/partialLogout.html
  scripts/shibboleth/postTemplate.html
  scripts/shibboleth/protocols.xml
  scripts/shibboleth/security-policy.xml
  scripts/shibboleth/sessionError.html
  scripts/shibboleth/shibd.logger
  scripts/shibboleth/sslError.html
  scripts/shibboleth/syslog.logger
  scripts/shibboleth/upgrade.xsl
  scripts/supervisor/celery-uclapi.conf
  scripts/supervisor/gunicorn-django.conf
  scripts/supervisor/nginx.conf
  scripts/supervisor/shib.conf
  scripts/supervisor/supervisord.conf
Labels: enhancement

#1046 More tests! 70%?! (Also 1 bug fix)
  backend/uclapi/dashboard/api_applications.py
  backend/uclapi/dashboard/tests.py
Labels: WIP

#1058 Compresses images
  frontend/src/images/logoCover.png
  frontend/src/images/logoCover2.png
  frontend/src/images/logoCover2_original.png
  frontend/src/images/logoCover_original.png
  frontend/src/images/marketplace_bg.png
  frontend/src/images/marketplace_bg_original.png
  frontend/src/images/roombuddy_screenshot1.png
  frontend/src/images/roombuddy_screenshot1_original.png
  frontend/src/images/roombuddy_screenshot2.png
  frontend/src/images/roombuddy_screenshot2_original.png
  frontend/src/images/roombuddy_screenshot3.png
  frontend/src/images/roombuddy_screenshot3_original.png
  frontend/src/images/roombuddylogo.png
  frontend/src/images/roombuddylogo_original.png
  frontend/src/images/signInWithUCLAPI.png
  frontend/src/images/signInWithUCLAPI_original.png
Labels: enhancement, ready to merge and deploy

#933 Readme and Contributing update
  CONTRIBUTING.md
  README.md
  backend/uclapi/.env.example
Labels: WIP, docs

#1033 Degree API
  backend/uclapi/dashboard/api_applications.py
  backend/uclapi/dashboard/tests.py
  backend/uclapi/requirements.txt
  backend/uclapi/timetable/app_helpers.py
  backend/uclapi/timetable/management/commands/update_timetable_gencache.py
  backend/uclapi/timetable/migrations/0008_coursea_courseb_crsavailmodulesa_crsavailmodulesb_crscompmodulesa_crscompmodulesb.py
  backend/uclapi/timetable/models.py
  backend/uclapi/timetable/tests.py
  backend/uclapi/timetable/urls.py
  backend/uclapi/timetable/views.py
  backend/uclapi/uclapi/dbrouters.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/documentation/Documentation.jsx
  frontend/src/components/documentation/Routes/OAuth/Token.jsx
  frontend/src/components/documentation/Routes/Timetable/GetDataCourses.jsx
  frontend/src/components/documentation/Routes/Timetable/GetDataCoursesModules.jsx
  frontend/src/components/documentation/Routes/Timetable/GetDataModules.jsx
  frontend/src/components/documentation/Sidebar.jsx
  frontend/src/components/getStarted/GitHub.jsx
  frontend/src/components/getStarted/getStarted.jsx
  frontend/src/images/logoCover.png
  frontend/src/images/logoCover2.png
  frontend/src/images/logoCover2_original.png
  frontend/src/images/logoCover_original.png
  frontend/src/images/marketplace_bg.png
  frontend/src/images/marketplace_bg_original.png
  frontend/src/images/roombuddy_screenshot1.png
  frontend/src/images/roombuddy_screenshot1_original.png
  frontend/src/images/roombuddy_screenshot2.png
  frontend/src/images/roombuddy_screenshot2_original.png
  frontend/src/images/roombuddy_screenshot3.png
  frontend/src/images/roombuddy_screenshot3_original.png
  frontend/src/images/roombuddylogo.png
  frontend/src/images/roombuddylogo_original.png
  frontend/src/images/signInWithUCLAPI.png
  frontend/src/images/signInWithUCLAPI_original.png
  frontend/src/sass/dashboard.scss
  frontend/src/sass/getStarted.scss
Labels: enhancement

#1059 Adds error message for invalid oauth callback url
  frontend/src/components/dashboard/app/OAuthCallbackField.jsx
Labels: ready to merge and deploy

#1092 Hotfix: Add check if module has attribute modgrpcode
  backend/uclapi/timetable/app_helpers.py
Labels: bug, high priority

#1089 add info about workspace caching in readme.md
  README.md
Labels: docs
