Repository uclapi/uclapi, pull requests merged in 2020-09, with the labels that each got.

#2790 ✂ Decouple dashboard from Django
  .gitignore
  backend/uclapi/.flake8.ini
  backend/uclapi/dashboard/api_applications.py
  backend/uclapi/dashboard/templates/dashboard.html
  backend/uclapi/dashboard/tests.py
  backend/uclapi/dashboard/urls.py
  backend/uclapi/dashboard/views.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/dashboard/App.jsx
  frontend/src/lib/Api.js
  frontend/src/pages/Dashboard.jsx
Labels: javascript, python

#2524 [WIP] Analytics and Logging
  backend/uclapi/common/decorators.py
  backend/uclapi/dashboard/api_applications.py
  backend/uclapi/dashboard/migrations/0015_auto_20200627_1627.py
  backend/uclapi/dashboard/models.py
  backend/uclapi/dashboard/tests.py
  backend/uclapi/dashboard/urls.py
  backend/uclapi/oauth/migrations/0003_oauthtoken_creation_date.py
  backend/uclapi/oauth/models.py
  frontend/.eslintignore
  frontend/.eslintrc.hound.json
  frontend/src/components/documentation/Documentation.jsx
  frontend/src/components/documentation/Routes/Analytics/MostPopularMethod.jsx
  frontend/src/components/documentation/Routes/Analytics/MostPopularService.jsx
  frontend/src/components/documentation/Routes/Analytics/RemainingQuota.jsx
  frontend/src/components/documentation/Routes/Analytics/TotalNumRequests.jsx
  frontend/src/components/documentation/Routes/Analytics/UsersPerApp.jsx
  frontend/src/components/documentation/Routes/Analytics/UsersPerAppPerDept.jsx
  frontend/src/components/documentation/Sidebar/MenuContent.jsx
Labels: docs, enhancement, python

#2794 Handle timetable events with no bookings
  backend/uclapi/timetable/app_helpers.py
  backend/uclapi/timetable/personal_timetable.py
  backend/uclapi/timetable/sql/generate_student_timetable_template.sql
Labels: timetable

#2795 🔨 Fix babel runtime error
  frontend/.babelrc
  frontend/package-lock.json
  frontend/package.json
Labels: bug, javascript

#2800 🐛 Add in missing function definition in docs
  frontend/src/components/documentation/Routes/OAuth/Authorise.jsx
Labels: bug, docs

#2818 ✂ Decouple Settings
  backend/uclapi/dashboard/templates/dashboard.html
  backend/uclapi/oauth/templates/permissions.html
  backend/uclapi/oauth/templates/settings.html
  backend/uclapi/oauth/urls.py
  backend/uclapi/oauth/views.py
  frontend/.eslintrc.hound.json
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/appsettings/LogInLayout.jsx
  frontend/src/components/appsettings/SettingsLayout.jsx
  frontend/src/lib/Api/DashboardApi.js
  frontend/src/lib/Api/SettingsApi.js
  frontend/src/lib/Api/index.js
  frontend/src/pages/AppSettings.jsx
  frontend/src/pages/Authorise.jsx
  frontend/src/pages/Authorise/Authorise.jsx
  frontend/src/pages/Authorise/Authorise.scss
  frontend/src/pages/Authorise/index.js
  frontend/src/pages/Dashboard/Dashboard.jsx
  frontend/src/pages/Dashboard/Dashboard.scss
  frontend/src/pages/Dashboard/index.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: enhancement, javascript
