Repository uclapi/uclapi, pull requests merged in 2020-07, with the labels that each got.

#2555 📦 update dependencies
  frontend/.eslintignore
  frontend/.eslintrc
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#2568 🐛 BUGFIX: Fix Authorise.jsx
  frontend/src/pages/Authorise.jsx
Labels: bug

#2446 Add date filter to documentation
  backend/uclapi/timetable/views.py
  frontend/src/components/documentation/Routes/Timetable/GetPersonalTimetable.jsx
  frontend/src/components/documentation/Routes/Timetable/GetTimetableByModules.jsx
Labels: docs
