Repository uclapi/uclapi, pull requests merged in 2021-06, with the labels that each got.

#3356 📦 dep: update codecov-action
  .github/workflows/CI.yml
Labels: dependencies

#3346 Switch to css-minimizer-webpack-plugin
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.prod.js
Labels: dependencies, javascript

#3378 Add version to cachet client creation
  backend/uclapi/common/cachet.py
Labels: bug
